In [2]:
import pandas as pd
url = "https://www.football-data.co.uk/mmz4281/2324/E0.csv"
pd.read_csv(url)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,E0,07/10/2023,17:30,Crystal Palace,Nott'm Forest,0,0,D,0,0,...,1.59,-0.25,1.99,1.94,1.98,1.94,2.03,2.01,1.94,1.91
76,E0,08/10/2023,14:00,Brighton,Liverpool,2,2,D,1,2,...,3.45,0.50,1.83,2.10,1.83,2.09,1.89,2.11,1.83,2.05
77,E0,08/10/2023,14:00,West Ham,Newcastle,2,2,D,1,0,...,2.08,0.25,2.03,1.78,2.10,1.82,2.10,1.93,2.01,1.83
78,E0,08/10/2023,14:00,Wolves,Aston Villa,1,1,D,0,0,...,2.03,0.50,1.85,2.08,1.85,2.08,1.88,2.10,1.83,2.05
79,E0,08/10/2023,16:30,Arsenal,Man City,1,0,H,0,0,...,1.82,0.25,1.73,2.08,1.78,2.17,1.85,2.23,1.76,2.11

In [3]:
#Create a variable and assign the data
# Show the data to the user using variable
url = "https://www.football-data.co.uk/mmz4281/2324/E0.csv"
pd.read_csv(url)
df_premier23 = pd.read_csv(url)
df_premier23

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,E0,07/10/2023,17:30,Crystal Palace,Nott'm Forest,0,0,D,0,0,...,1.59,-0.25,1.99,1.94,1.98,1.94,2.03,2.01,1.94,1.91
76,E0,08/10/2023,14:00,Brighton,Liverpool,2,2,D,1,2,...,3.45,0.50,1.83,2.10,1.83,2.09,1.89,2.11,1.83,2.05
77,E0,08/10/2023,14:00,West Ham,Newcastle,2,2,D,1,0,...,2.08,0.25,2.03,1.78,2.10,1.82,2.10,1.93,2.01,1.83
78,E0,08/10/2023,14:00,Wolves,Aston Villa,1,1,D,0,0,...,2.03,0.50,1.85,2.08,1.85,2.08,1.88,2.10,1.83,2.05
79,E0,08/10/2023,16:30,Arsenal,Man City,1,0,H,0,0,...,1.82,0.25,1.73,2.08,1.78,2.17,1.85,2.23,1.76,2.11

In [4]:
# Reaname column headings
df_premier23.rename(columns={'FTHG':'home_goals',
                            'FTAG':'away_goals'}, inplace=True)

# Show data frame
df_premier23

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,E0,07/10/2023,17:30,Crystal Palace,Nott'm Forest,0,0,D,0,0,...,1.59,-0.25,1.99,1.94,1.98,1.94,2.03,2.01,1.94,1.91
76,E0,08/10/2023,14:00,Brighton,Liverpool,2,2,D,1,2,...,3.45,0.50,1.83,2.10,1.83,2.09,1.89,2.11,1.83,2.05
77,E0,08/10/2023,14:00,West Ham,Newcastle,2,2,D,1,0,...,2.08,0.25,2.03,1.78,2.10,1.82,2.10,1.93,2.01,1.83
78,E0,08/10/2023,14:00,Wolves,Aston Villa,1,1,D,0,0,...,2.03,0.50,1.85,2.08,1.85,2.08,1.88,2.10,1.83,2.05
79,E0,08/10/2023,16:30,Arsenal,Man City,1,0,H,0,0,...,1.82,0.25,1.73,2.08,1.78,2.17,1.85,2.23,1.76,2.11